config/routes.rb
Rails.application.routes.draw do

  root to: 'links#index'
  match("/upvote", {via:[:get, :post], to: "links#upvote"})
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users
  resources :links

end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :user

  def age
    ((Time.now - self.created_at) / 1.hour).round
  end

  def rank
    self.votes / (self.age + 1)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :name, uniqueness: true
  # validates :email, uniqueness: true
  # validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_filter :authorize, only: [:new, :edit, :update]

  def index
    @links = Link.all.sort {|x, y| y.rank <=> x.rank}
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params.merge user_id: current_user.id)
    if @link.save
      redirect_to root_path, notice: "Thanks for submitting!"
    else
      render "new"
    end
  end

  def upvote
    @links = Link.all.sort {|x, y| y.rank <=> x.rank}
    link = Link.find(params[:id])
    link.update(votes: link.votes + 1)
    redirect_to root_path, notice: "Thanks for voting."
  end

private
  def link_params
    params.require(:link).permit(:name, :url, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Login or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Thanks for signing up!"
    else
      render "new"
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle " data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Link Tracker</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Submit Link", new_link_path %></li>
        <% if current_user %>
          <li><a href="">Logged in as <%= current_user.name %></a></li>
          <li><%= link_to "Log Out", logout_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<%= flash[:alert] %>
<%= flash[:notice] %>


<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<% content_for(:title, "Links | Hacker Clone") %>

<ul>
  <% @links.each do |link| %>
    <li><%= link_to "+", upvote_path(:id => link.id) %><%= link_to link.name, url_for(link.url)%>
        <ul><li>Votes: <%= link.votes %> by <%=link.user.name%> <%= link.age %> hours ago</li></ul>
    </li>
  <%end%>
</ul>

app/views/links/new.html.erb
<h1>Submit</h1>

<%= render("layouts/errors", :object => @link) %>

<%= form_for @link do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>

  <div class="actions"><%= f.submit "Submit" %></div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render("layouts/errors", :object => @user) %>

<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>